wip

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -36,9 +36,9 @@ runs:
         if [[ $exit_code == 0 ]]; then
           echo "success"
         elif [[ $exit_code == 1 ]]; then
-          echo "::warning:: not compatible"
+          echo "::warning::not compatible"
           exit 1
         else
-          echo "::error:: execution failed, exit_code=$exit_code"
-          exit 1
+          echo "::error::execution failed, exit_code=$exit_code"
+          exit 2
         fi
